# Generated by Django 4.2 on 2023-04-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_userprofile_assigned_interviewee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
