# Generated by Django 4.2 on 2023-04-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_userprofile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="image",
            new_name="profile_image",
        ),
    ]
