# Generated by Django 4.2 on 2023-04-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_userprofile_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_crop_dimension", models.PositiveIntegerField(default=300)),
            ],
            options={
                "verbose_name_plural": "App Configurations",
            },
        ),
    ]
